### ISSUE TITLE
Merged code reverted

### ISSUE THREAD

**Issue by rodineijf** [Skyost/BubbleShowcase#14]
Last year [this pull request](https://github.com/Skyost/BubbleShowcase/pull/4) was merged, but it was reverted by [this  commit](https://github.com/Skyost/BubbleShowcase/commit/fd36037f76c53730cab6a0fbb438e25208ab44d6).

Was this intended? What are your thoughts about this code?

**Comment by Skyost** [comment]
Hmmm… I think I've reverted it because it has messed up various things in the code (and if I remember correctly, issues like #6 and #12 were difficult to handle because of that).

But if you're still interested in this feature, I can work on that when I will have some free time (which will be the case at the beginning of July).

**Comment by rodineijf** [comment]
I'll try to implement these features again without harm the existing behavior. We are updating our app to null safety, so anyhow, I'll have to work on this.

I'm gonna open a PR soon. Thank you.

**Comment by Skyost** [comment]
That's okay ! :wink:
